// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://guqwmwhesevvdsblynip.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd1cXdtd2hlc2V2dmRzYmx5bmlwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4ODE1MzQsImV4cCI6MjA2OTQ1NzUzNH0.8-hcF-7X2r0AiC_oeERkcicqJhDqTPVwH9C9Sz9BGc4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});